name: Verify Kubespray

on:
  workflow_dispatch: #manual run
  schedule:
    - cron: '0 18 * * *'

jobs:
  output-variable:
    runs-on: ubuntu-latest
    outputs:
      repo: ${{ steps.output_variables.outputs.repo }}
      spray_version: ${{ steps.output_variables.outputs.spray_version }}
      spray_short_sha: ${{ steps.output_variables.outputs.spray_short_sha }}
      container_tag: ${{ steps.output_variables.outputs.container_tag }}
    steps:
    - name: output environment variable
      id: output_variables
      run: |
        spray_version=`git ls-remote --head https://github.com/kubernetes-sigs/kubespray.git refs/heads/master | awk -F ' ' '{print $1}'`
        echo spray_version=${spray_version} >> $GITHUB_OUTPUT
        echo spray_short_sha=$(echo ${spray_version} | cut -c 1-7) >> $GITHUB_OUTPUT
        ORGANIZATION_NAME=$(echo ${GITHUB_REPOSITORY} | awk -F "/" '{print $1}' | tr '[:upper:]' '[:lower:]')
        echo repo=${ORGANIZATION_NAME} >> $GITHUB_OUTPUT
        CONTAINER_TAG=$(git describe --tags --abbrev=8 --dirty)
        if [[ ${{ inputs.CI_TYPE }} == "main" ]]; then
          echo container_tag="${CONTAINER_TAG}-main" >> $GITHUB_OUTPUT
        else
          echo container_tag=${CONTAINER_TAG} >> $GITHUB_OUTPUT
        fi
  build-spray-imgs:
    needs: output-variable
    uses: ./.github/workflows/call-build-imgs-for-spray.yaml
    secrets: inherit
    with:
      SPRAY_REF: ${{ needs.output-variable.outputs.spray_version }}
      REPO: ${{ needs.output-variable.outputs.repo }}

  build-kubean-imgs:
    needs: [output-variable, build-spray-imgs]
    uses: ./.github/workflows/call-build-imgs-for-kubean.yaml
    secrets: inherit
    with:
      SPRAY_IMG_TAG: ${{ needs.output-variable.outputs.spray_short_sha }}
      REPO: ${{ needs.output-variable.outputs.repo }}
      BUILD_IMG_TAG: ${{ needs.output-variable.outputs.container_tag }}